import Head from "next/head";
import Main from "./main/main";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Sneakers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/tenis-de-corrida.png" />
      </Head>
      <Main />
    </div>
  );
}
