import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/main.module.css'
import Cards from '../components/Cards'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Sneakers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/tenis-de-corrida.png" />
      </Head>
      <div className={styles.container}>
            <Cards/>
    </div>
  </div>
  )
}
